//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHockey
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matches
    {
        public int IDmatch { get; set; }
        public int IDCommand1 { get; set; }
        public int IDCommand2 { get; set; }
        public Nullable<System.DateTime> DateMatch { get; set; }
        public string TypeCompetition { get; set; }
        public string Command1 { get; set; }
        public string Command2 { get; set; }
        public string Result { get; set; }
    
        public virtual Participants Participants { get; set; }
        public virtual Participants Participants1 { get; set; }
    }
}
