//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHockey
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participants
    {
        public Participants()
        {
            this.Matches = new HashSet<Matches>();
            this.Matches1 = new HashSet<Matches>();
            this.Sostav = new HashSet<Sostav>();
        }
    
        public int IDcommand { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public Nullable<int> Countmatches { get; set; }
        public Nullable<int> Win { get; set; }
        public Nullable<int> Lose { get; set; }
        public Nullable<int> Draw { get; set; }
        public Nullable<int> Glasses { get; set; }
        public string Achievement { get; set; }
    
        public virtual ICollection<Matches> Matches { get; set; }
        public virtual ICollection<Matches> Matches1 { get; set; }
        public virtual ICollection<Sostav> Sostav { get; set; }
    }
}
